services:
  - type: web
    name: backend-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000  # Render will override this, but useful to declare
      - key: RESEND_API_KEY
        sync: false   # Set in the Render Dashboard or .env
      - key: ADMIN_EMAIL
        sync: false
    autoDeploy: true
    buildFilter:
      paths:
        - src/backend/**
    rootDir: src/backend
